from __future__ import annotations

from ghostmesh.domain import PermissionName

PATCH_PANEL_CREATE = PermissionName.PATCH_PANEL_CREATE
PATCH_PANEL_EDIT_DRAFT = PermissionName.PATCH_PANEL_EDIT_DRAFT
PATCH_PANEL_PUBLISH_VERSION = PermissionName.PATCH_PANEL_PUBLISH_VERSION
PATCH_PANEL_ARCHIVE = PermissionName.PATCH_PANEL_ARCHIVE
PATCH_PANEL_DISCOVER = PermissionName.PATCH_PANEL_DISCOVER
BUCKET_CREATE = PermissionName.BUCKET_CREATE
NODE_CREATE = PermissionName.NODE_CREATE
EDGE_CREATE = PermissionName.EDGE_CREATE
PIPE_BINDING_CREATE = PermissionName.PIPE_BINDING_CREATE
CARD_CREATE = PermissionName.CARD_CREATE
CARD_CLAIM = PermissionName.CARD_CLAIM
CARD_SUBMIT_ARTIFACT = PermissionName.CARD_SUBMIT_ARTIFACT
CARD_RELEASE = PermissionName.CARD_RELEASE
CARD_VIEW = PermissionName.CARD_VIEW
VALIDATION_SUBMIT = PermissionName.VALIDATION_SUBMIT
MUTATION_PROPOSE = PermissionName.MUTATION_PROPOSE
MUTATION_VALIDATE = PermissionName.MUTATION_VALIDATE
MUTATION_PROMOTE = PermissionName.MUTATION_PROMOTE
SHADOW_CREATE = PermissionName.SHADOW_CREATE
SHADOW_COMPLETE = PermissionName.SHADOW_COMPLETE
SINK_EXECUTE = PermissionName.SINK_EXECUTE
BOUNDARY_SOURCE_INGRESS = PermissionName.BOUNDARY_SOURCE_INGRESS
BOUNDARY_SINK_EGRESS = PermissionName.BOUNDARY_SINK_EGRESS
PARTICIPANT_MANAGE = PermissionName.PARTICIPANT_MANAGE
PERMISSION_GRANT = PermissionName.PERMISSION_GRANT
AUDIT_VIEW = PermissionName.AUDIT_VIEW

ALL_PERMISSIONS = tuple(PermissionName)
